import { base, colors } from "@/theme";
import { StyleSheet } from "react-native";

export const apiTesterStyles = StyleSheet.create({
  scroll: { flex: 1, backgroundColor: colors.bg },
  container: { padding: 16, paddingBottom: 40 },
  section: { marginBottom: 24 },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.text,
    marginBottom: 8,
  },
  label: { fontSize: 12, color: colors.muted, marginBottom: 6 },
  methodRow: { ...base.row, marginBottom: 10 },
  methodBtn: { ...base.btn, paddingHorizontal: 10 },
  methodBtnActive: base.btnActive,
  methodText: { ...base.textMuted, fontSize: 12, fontWeight: "600" },
  methodTextActive: base.textActive,
  urlInput: {
    ...base.card,
    padding: 10,
    color: colors.text,
    fontSize: 14,
    marginBottom: 10,
  },
  tabRow: { ...base.row, gap: 4, marginBottom: 10 },
  tab: base.btn,
  tabActive: base.btnActive,
  tabText: { ...base.textMuted, fontSize: 13 },
  tabTextActive: base.textActive,
  bodySection: { marginBottom: 10 },
  bodyTypeRow: { ...base.row, gap: 4, marginBottom: 8 },
  bodyTypeBtn: { ...base.btn, paddingHorizontal: 10, paddingVertical: 6 },
  bodyTypeBtnActive: { backgroundColor: colors.text, borderColor: colors.text },
  bodyTypeText: { ...base.textMuted, fontSize: 12 },
  bodyTypeTextActive: base.textActive,
  bodyInput: {
    ...base.card,
    padding: 10,
    color: colors.text,
    fontSize: 13,
    minHeight: 80,
  },
  authSection: { marginBottom: 12 },
  authTypeRow: { ...base.row, marginBottom: 8 },
  authTypeBtn: base.btn,
  authTypeBtnActive: base.btnActive,
  authTypeText: { ...base.textMuted, fontSize: 12 },
  authTypeTextActive: base.textActive,
  authInput: {
    ...base.card,
    padding: 10,
    color: colors.text,
    fontSize: 14,
    marginBottom: 8,
  },
  apiKeyLocRow: { ...base.row, marginBottom: 8 },
  apiKeyLocBtn: base.btn,
  apiKeyLocBtnActive: base.btnActive,
  apiKeyLocText: { ...base.textMuted, fontSize: 12 },
  apiKeyLocTextActive: base.textActive,
  sendBtn: {
    backgroundColor: colors.primary,
    paddingVertical: 12,
    borderRadius: 6,
    alignItems: "center",
  },
  sendBtnDisabled: { opacity: 0.6 },
  sendBtnText: { color: colors.white, fontWeight: "600", fontSize: 16 },
  responseHeader: {
    ...base.row,
    alignItems: "center",
    gap: 10,
    marginBottom: 8,
  },
  statusText: { fontSize: 16, fontWeight: "bold" },
  timeText: { ...base.textMuted, fontSize: 13 },
  copyBtn: { marginLeft: "auto", padding: 4 },
  copyBtnText: { color: colors.primary, fontSize: 13 },
  responseTabRow: { ...base.row, gap: 4, marginBottom: 8 },
  responseTab: base.btn,
  responseTabActive: base.btnActive,
  responseTabText: { ...base.textMuted, fontSize: 13 },
  responseTabTextActive: base.textActive,
  responseBody: { maxHeight: 280, ...base.card, padding: 10 },
  rawText: { ...base.text, fontSize: 12 },
  errorText: { color: colors.danger, fontSize: 13 },
  headersList: { ...base.card, padding: 10 },
  headerRow: { marginBottom: 6 },
  headerKey: { color: colors.link, fontSize: 12, marginBottom: 2 },
  headerVal: { ...base.text, fontSize: 12 },
  emptyText: { color: colors.placeholder, fontSize: 13 },
});
